//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurence.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestimonial
    {
        public int TestimoniaLId { get; set; }
        public string NameSurname { get; set; }
        public string Profession { get; set; }
        public string Text { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Rating { get; set; }
        public string DescriptionEN { get; set; }
        public string ProfessionEN { get; set; }
    }
}
